services:
  - type: web
    name: tiberbu-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn tiberbu_backend.wsgi:application --log-file -
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tiberbu-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: tiberbu_backend.onrender.com

databases:
  - name: tiberbu-db
    databaseName: tiberbu_db
    user: tiberbu_user
