# Generated by Django 4.2.20 on 2025-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
            preserve_default=False,
        ),
    ]
